#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.seaweedfs_volume.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: seaweedfs-volume
  ports:
  - port: 8080
    name: volume-server-port
  - port: 18080
    name: volume-grpc-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seaweedfs-volume
  name: deployment-seaweedfs-volume
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: seaweedfs-volume
        image: {{ .Values.images.seaweedfs_image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: vol-seaweed-volume-data
          mountPath: /data
        args: ["volume", "-mserver={{ .Values.config.seaweedfs_master.name }}:9333", "-ip.bind=0.0.0.0", "-port=8080"]
        env:
        - name: NO_PROXY
          value: "localhost,127.0.0.1,{{ .Values.config.seaweedfs_filer.name }},{{ .Values.config.seaweedfs_volume.name }},{{ .Values.config.seaweedfs_master.name }},{{ .Values.config.seaweedfs_s3.name }},172.18.0.0/16"
        - name: no_proxy
          value: "localhost,127.0.0.1,{{ .Values.config.seaweedfs_master.name }},{{ .Values.config.seaweedfs_volume.name }},{{ .Values.config.seaweedfs_filer.name }},{{ .Values.config.seaweedfs_s3.name }},172.18.0.0/16"
      volumes:
      - name: vol-seaweed-volume-data
        emptyDir: {}