#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.seaweedfs_filer.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: filer-http-port
    port: 8888 
  - name: filer-grpc-port
    port: 18888
  selector:
    app: seaweedfs-filer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seaweedfs-filer
  name: deployment-seaweedfs-filer
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: seaweedfs-filer
  template:
    metadata:
      labels:
        app: seaweedfs-filer
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: seaweedfs-filer
        image: {{ .Values.images.seaweedfs_image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: vol-temp-seaweed-filer
          mountPath: /tmp
        - name: vol-seaweed-filer-data
          mountPath: /data
        args: ["filer", "-master={{ .Values.config.seaweedfs_master.name }}:9333", "-ip.bind=0.0.0.0"]
        env:
        - name: NO_PROXY
          value: "localhost,127.0.0.1,{{ .Values.config.seaweedfs_filer.name }},{{ .Values.config.seaweedfs_volume.name }},{{ .Values.config.seaweedfs_master.name }},{{ .Values.config.seaweedfs_s3.name }},172.18.0.0/16"
        - name: no_proxy
          value: "localhost,127.0.0.1,{{ .Values.config.seaweedfs_filer.name }},{{ .Values.config.seaweedfs_volume.name }},{{ .Values.config.seaweedfs_master.name }},{{ .Values.config.seaweedfs_s3.name }},172.18.0.0/16"
      volumes:
      - name: vol-temp-seaweed-filer
        emptyDir: {}
      - name: vol-seaweed-filer-data
        emptyDir: {}